---
# tasks file for kube-prometheus
- name: "Get promtheus-k8s svc"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: monitoring
    name: monitoring
  register: promtheus_k8s_service

- name: "print promtheus_k8s_service"
  ansible.builtin.debug:
    var: promtheus_k8s_service

- name: "check out kube-prometheus"
  when: "not promtheus_k8s_service.api_found"
  ansible.builtin.git:
    repo: "https://github.com/prometheus-operator/kube-prometheus"
    dest: ~/kube-prometheus

- name: "apply kube-prometheus setup"
  when: "not promtheus_k8s_service.api_found"
  kubernetes.core.k8s:
    src: "{{ item }}"
    state: present
  with_fileglob:
      - ~/kube-prometheus/manifests/setup/*
  ignore_errors: yes

- name: "apply kube-prometheus"
  when: "not promtheus_k8s_service.api_found"
  kubernetes.core.k8s:
    src: "{{ item }}"
    state: present      
  with_fileglob:
      - ~/kube-prometheus/manifests/*

